server:
  port: 9527
spring:
  application:
    name: zuul-gateway

zuul:
  routes:
    sysmanage.serviceId: hrm-management # 服务名
    sysmanage.path: /sysmanage/** # 把hrm-management打头的所有请求都转发给sysmanage
    course.serviceId: hrm-course # 服务名
    course.path: /course/** # 把hrm-course打头的所有请求都转发给course
    fastdfs.serviceId: hrm-fastdfs # 服务名
    fastdfs.path: /fastdfs/** # 把hrm-course打头的所有请求都转发给course
    es.serviceId: hrm-es # 服务名
    es.path: /es/** # 把hrm-es打头的所有请求都转发给course
    redis.serviceId: hrm-redis # 服务名
    redis.path: /redis/** # 把hrm-es打头的所有请求都转发给course
    page.serviceId: hrm-page # 服务名
    page.path: /page/** # 把hrm-es打头的所有请求都转发给course
    pageAgent.serviceId: hrm-page-agent # 服务名
    pageAgent.path: /pageAgent/** # 把hrm-es打头的所有请求都转发给course
  ignored-services: "*" #所有服务都不允许以服务名来访问
  prefix: "/services" #加一个统一前缀
  retryable: true #是否重试
ribbon:
  ConnectTimeout: 250 # 连接超时时间(ms)
  ReadTimeout: 2000 # 通信超时时间(ms)
  OkToRetryOnAllOperations: true # 是否对所有操作重试
  MaxAutoRetriesNextServer: 2 # 同一服务不同实例的重试次数
  MaxAutoRetries: 1 # 同一实例的重试次数
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 3000 # 熔断超时时长：3000ms
