server:
  port: 9002
spring:
  application:
    name: hrm-course
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/hrm_course
      username: root
      password: 44944
mybatis-plus:
  mapper-locations: classpath:com/wyz/hrm/mapper/*Mapper.xml
  type-aliases-package: com.wyz.hrm.domain,com.wyz.hrm.query